name: 'ci'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 13 * * 0,3'

permissions: read-all

jobs:
  test-schedule:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Updates'
        run: ./bake run-python