name: 'ci'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 13 * * 0,3'

permissions: read-all

jobs:
  star-generator:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: 'Run Python Star Generator'
        run: ./bake run-python