name: 'ci'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 13 * * 0,3'

jobs:
  star-generator:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: 'Run Python Star Generator'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: ./bake run-python
      - uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: '${{ github.ref }}'
       